RoomReservationSystem/RoomReservationSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservationapp/', include('reservationapp.urls')),
]

RoomReservationSystem/reservationapp/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = "reservationapp"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home", Home.as_view(), name="home"),
    path("login", Login.as_view(), name="login"),
    path("logout", Logout.as_view(), name="logout"),
    path("sign-up", SignUp.as_view(), name="signup"),
    path("list-organizations", ListOrganizations.as_view(), name="list-organizations"),
    path("organization", OrganizationView.as_view(), name="organization"),
    path("save", Save.as_view(), name="save"),
    path("room", roomView.as_view(), name="room"),
    path("map", MapView.as_view(), name="map"),
    path("event", EventView.as_view(), name="event"),
    path("dayView", DayView.as_view(), name="dayView"),
    path("roomView", RoomView.as_view(), name="roomView"),
    path("add-room", AddRoomView.as_view(), name="add-room"),
    path("eventUpdate", EventUpdate.as_view(), name="eventUpdate"),
]

RoomReservationSystem/templates/add-room-page.html
{% extends 'index.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/my_profile.css' %}?v1.3">
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
  <title>Organization Page</title>

{% endblock %}
<style>
  .form-right{
    width: 300px;
    margin-right: 20px;
    margin-top: 10px;
  }
</style>

{% block content %}
  <li class="selected">
    <div class="cd-full-width">
      <div class="container-fluid js-tm-page-content tm-page-pad" data-page-no="5" data-page-type="gallery">
                <br><br><br>
                <div class="container">
                    {% if user_authenticated %}
                    
                      <div style="display: flex; justify-content: flex-end;">
                        <div class="form-right">
                          <form action="{% url 'reservationapp:add-room' %}" class="add-room" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <input type="hidden" name="orgServerId" value="{{ orgServeId }}">
                            <input type="hidden" name="orgName" value="{{ orgName }}">
                            <input type="hidden" name="addRoom" value="true">
                            <Button style="margin-top: 5px;" class="btn btn-dark btn-lg" type="submit">Add Room</Button>
                          </form>
                          <form action="{% url 'reservationapp:map' %}" class="map" method="get" >
                            {% csrf_token %}
                            <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                            <input type="hidden" name="orgName" value="{{ orgName }}">
                            <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Back</Button>
                          </form> 
                        </div>
                      </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </li>


{% endblock %}

RoomReservationSystem/templates/dayView.html
{% extends 'index.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/my_profile.css' %}?v1.3">
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
  <title>Organization Page</title>

{% endblock %}
<style>
  .form-right{
    width: 300px;
    margin-right: 20px;
    margin-top: 10px;
  }
</style>

{% block content %}
  <li class="selected">
    <div class="cd-full-width">
      <div class="container-fluid js-tm-page-content tm-page-pad" data-page-no="5" data-page-type="gallery">
                <br><br><br>
                <div class="container">
                    {% if user_authenticated %}
                    <h1 style="font-size: 32px; margin-bottom: 8px">Day Organization: {{ orgName }}</h1>
                    
                    {% if events %}
                      {% for key, value in events.items %}
                        <table id="eventTable">
                          <thead>
                            <tr>
                              <th>{{key}}</th>
                      
                            </tr>
                          </thead>
                          <tbody>
                            {% for val in value %}
                            <tr>
                              
                                <td>{{val.1}}</td>
                                <td>
                                  <form action="{% url 'reservationapp:eventUpdate' %}" class="eventUpdate" method="get" >
                                  {% csrf_token %}
                                  <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                                  <input type="hidden" name="orgName" value="{{ orgName }}">
                                  <input type="hidden" name="eventId" value="{{ val.0 }}">
                                  <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Info</Button>
                                  </form> 
                                </td>
                            </tr>
                            
                            {% endfor %}
                            
                          </tbody>
                        </table>
                        
                        
                      {% endfor %}
                    {% endif %}
                    <form action="{% url 'reservationapp:dayView' %}" class="dayView" method="post" >
                      {% csrf_token %}
                      <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                      <input type="hidden" name="orgName" value="{{ orgName }}">
                      <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">List Events</Button>
                    </form> 
                    <form action="{% url 'reservationapp:event' %}" class="event" method="get" >
                      {% csrf_token %}
                      <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                      <input type="hidden" name="orgName" value="{{ orgName }}">
                      <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Back</Button>
                    </form> 
                    {% endif %}
                </div>
                
            </div>
        </div>
    </li>


{% endblock %}

RoomReservationSystem/templates/event.html
{% extends 'index.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/my_profile.css' %}?v1.3">
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
  <title>Organization Page</title>

{% endblock %}
<style>
  .form-right{
    width: 300px;
    margin-right: 20px;
    margin-top: 10px;
  }
</style>

{% block content %}
  <li class="selected">
    <div class="cd-full-width">
      <div class="container-fluid js-tm-page-content tm-page-pad" data-page-no="5" data-page-type="gallery">
                <br><br><br>
                <div class="container">
                    {% if user_authenticated %}
                        <form action="{% url 'reservationapp:event' %}" class="event" method="post" >
                            {% csrf_token %}
                            {{form.as_p}}
                            <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                            <input type="hidden" name="orgName" value="{{ orgName }}">
                            <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Search Events</Button>
                        </form> 
                        
                        <div style="display: flex; justify-content: flex-end;"></div>
                          <div class="form-right">
                            <form action="{% url 'reservationapp:dayView' %}" class="dayView" method="get">
                              {% csrf_token %}
                              <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                              <input type="hidden" name="orgName" value="{{ orgName }}">
                              <Button style="margin-top: 5px;" class="btn btn-dark btn-lg" type="submit">Events by Days</Button>
                            </form>
                          </div>
                        </div> 

                        <div style="display: flex; justify-content: flex-end;"></div>
                          <div class="form-right">
                            <form action="{% url 'reservationapp:roomView' %}" class="roomView" method="get">
                              {% csrf_token %}
                              <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                              <input type="hidden" name="orgName" value="{{ orgName }}">
                              <Button style="margin-top: 5px;" class="btn btn-dark btn-lg" type="submit">Events by Rooms</Button>
                            </form>
                          </div>
                        </div>
                        
                        <form action="{% url 'reservationapp:organization' %}" class="organization" method="get" >
                          {% csrf_token %}
                          <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                          <input type="hidden" name="orgName" value="{{ orgName }}">
                          <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Back</Button>
                        </form>  
                        {% if queryResult %}
                            <div class="row">
                                {% for eventTitle,eventDescription,eventCategory,room,start in queryResult %}
                                    <h3 style="margin-top:100px">Event title: {{ eventTitle }}</h3>
                                    <p> <b> Category: {{ eventCategory}} </b></p>
                                    <p> <b> Description: {{ eventDescription}} </b></p>
                                    <p> <b> Room: {{ room}} </b></p>
                                    <p> <b> Start time: {{ start}} </b></p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </li>


{% endblock %}

RoomReservationSystem/templates/homepage.html
{% extends 'index.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/my_profile.css' %}?v1.3">
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
    <title>Homepage</title>

{% endblock %}


{% block content %}
    <li class="selected">
        <div class="cd-full-width">
            <div class="container-fluid js-tm-page-content tm-page-pad" data-page-no="5" data-page-type="gallery">
                <br><br><br>
                <div class="container">
                    {% if user_authenticated %}
                      {% if organizations %}
                        <div class="row">
          
                        {% for org in organizations %}
                            
                          <h3 style="margin-top:100px">Organization name: {{ org.org_name }}</h3>
                          <p> <b> Organization owner: {{ org.org_owner}} </b></p>
                          <form action="{% url 'reservationapp:list-organizations' %}" class="list-organizations" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="orgServerId" value="{{ org.org_id }}">
                            <input type="hidden" name="orgName" value="{{ org.org_name }}">
                            <Button style="margin-top: 5px;" class="btn btn-dark btn-lg" type="submit">Attach Organization</Button>
                          </form>
                             
                        {% endfor %}
 
                        </div>
                      {% endif %}
                      <h1 style="font-size: 32px; margin-bottom: 8px">Welcome, {{ user.username }}</h1>
                      <form action="{% url 'reservationapp:list-organizations' %}" class="list-organizations" method="get" >
                        {% csrf_token %}
                        <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">List Organizations</Button>
                      </form>

                    {% else %}
                      <form action="{% url 'reservationapp:login' %}" class="login" method="post" >
                        {% csrf_token %}
                        {{ form|crispy }}
                        <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Login</Button>
                        <br>
                        <small style="margin-top: 5px">Don't have an account? <a href="{% url 'reservationapp:signup' %}"><i class="fas fa-user-plus"></i></a> </small>
                        
                      </form>
                    {% endif %}


                </div>
            </div>
        </div>
    </li>


{% endblock %}

RoomReservationSystem/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


{#    <title>Room Reservation App</title>#}
<!--

Template 2086 Multi Color

http://www.tooplate.com/view/2086-multi-color

-->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <!-- Google web font "Open Sans" -->
{#    <link rel="stylesheet" href="../../../static/font-awesome-4.5.0/css/font-awesome.min.css">#}
    <link rel="stylesheet" href="{% static 'font-awesome-4.5.0/css/font-awesome.min.css' %}">
    <!-- Font Awesome -->
{#    <link rel="stylesheet" href="../../../static/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
    <!-- Bootstrap style -->
{#    <link rel="stylesheet" href="../../../static/css/hero-slider-style.css">#}
    <link rel="stylesheet" href="{% static 'css/hero-slider-style.css' %}">
    <!-- Hero slider style (https://codyhouse.co/gem/hero-slider/) -->
{#    <link rel="stylesheet" href="../../../static/css/magnific-popup.css">#}
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- Magnific popup style (http://dimsemenov.com/plugins/magnific-popup/) -->
{#    <link rel="stylesheet" href="../../../static/css/tooplate-style.css">#}
    <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}?v1.3">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
{#          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>#}
{#          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>#}
          <![endif]-->

    {% block head %}
    {% endblock %}
</head>

    <body>

        <!-- Content -->
        <div class="cd-hero">

            <!-- Navigation -->        
            <div style="margin-bottom: 50px" class="cd-slider-nav">
                <nav style="margin-bottom: 50px" class="navbar">

                    <div class="tm-navbar-bg">

                        <a class="navbar-brand text-uppercase" href="#"><i class="fa fa-calendar-o"></i>Room Reservation</a>
                        <div align="right" style="width: 650px; margin-right: 20px">
                            
                            <a class="nav-link" href="{% url 'reservationapp:login' %}"><i class="fa fa-calendar-o"></i>Login</a>

                        </div>

                        <div align="middle" style="width: 650px; margin-right: 20px">
                            
                            <a class="nav-link" href="{% url 'reservationapp:save' %}"><i class="fa fa-calendar-o"></i>Save</a>

                        </div>

                        <div align="right" style="width: 650px; margin-right: 20px">
                            
                            <a class="nav-link" href="{% url 'reservationapp:logout' %}"><i class="fa fa-calendar-o"></i>Logout</a>
                        
                        </div>

                        {% block contains_link %}

                        {% endblock %}



{#                        <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#tmNavbar">#}
{#                            &#9776;#}
{#                        </button>#}
{#                        <ul class="nav navbar-nav">#}
{#                                <li class="nav-item active selected">#}
{#                                    <a class="nav-link" href="{% url 'reservationapp:organizations' %}" data-no="1">All Organizations<span class="sr-only">(current)</span></a>#}
{#                                </li>#}
{#                                <li class="nav-item">#}
{#                                    <a class="nav-link" href="#0" data-no="2">Multi Two</a>#}
{#                                </li>#}
{#                                <li class="nav-item">#}
{#                                    <a class="nav-link" href="#0" data-no="3">Multi Three</a>#}
{#                                </li>#}
{#                                <li class="nav-item">#}
{#                                    <a class="nav-link" href="#0" data-no="4">Our Team</a>#}
{#                                </li>#}
{#                                <li class="nav-item">#}
{#                                    <a class="nav-link" href="#0" data-no="5">Keep in touch</a>#}
{#                                </li>#}
{#                            </ul>#}
                    </div>

                </nav>
            </div>



            <ul class="cd-hero-slider">
                {% block content %}
                {% endblock %}
            </ul> <!-- .cd-hero-slider -->

{#            <footer class="tm-footer">#}
{#            #}
{#                <div class="tm-social-icons-container text-xs-center">#}
{#                    <a href="#" class="tm-social-link"><i class="fa fa-facebook"></i></a>#}
{#                    <a href="#" class="tm-social-link"><i class="fa fa-google-plus"></i></a>#}
{#                    <a href="#" class="tm-social-link"><i class="fa fa-twitter"></i></a>#}
{#                    <a href="#" class="tm-social-link"><i class="fa fa-behance"></i></a>#}
{#                    <a href="#" class="tm-social-link"><i class="fa fa-linkedin"></i></a>#}
{#                </div>#}
{#                #}
{#                <p class="tm-copyright-text">Copyright &copy; 2017 Your Company #}
{#                #}
{#                 - Design: Tooplate</p>#}
{##}
{#            </footer>#}
                    
        </div> <!-- .cd-hero -->
        

        <!-- Preloader, https://ihatetomatoes.net/create-custom-preloading-screen/ -->
        <div id="loader-wrapper">
            
            <div id="loader"></div>
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>

        </div>
        
        <!-- load JS files -->
{#        <script src="../../../static/js/jquery-1.11.3.min.js"></script>         <!-- jQuery (https://jquery.com/download/) -->#}
{#        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap (http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h) --> #}
{#        <script src="../../../static/js/bootstrap.min.js"></script>             <!-- Bootstrap js (v4-alpha.getbootstrap.com/) -->#}
{#        <script src="../../../static/js/hero-slider-main.js"></script>          <!-- Hero slider (https://codyhouse.co/gem/hero-slider/) -->#}
{#        <script src="../../../static/js/jquery.magnific-popup.min.js"></script> <!-- Magnific popup (http://dimsemenov.com/plugins/magnific-popup/) -->#}
{#        #}
        <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>         <!-- jQuery (https://jquery.com/download/) -->
{#        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap (http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h) -->#}
{#        <script src="{% static 'js/bootstrap.min.js' %}"></script>             <!-- Bootstrap js (v4-alpha.getbootstrap.com/) -->#}
        <script src="{% static 'js/hero-slider-main.js' %}"></script>          <!-- Hero slider (https://codyhouse.co/gem/hero-slider/) -->
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> <!-- Magnific popup (http://dimsemenov.com/plugins/magnific-popup/) -->

        <script>

            function adjustHeightOfPage(pageNo) {

                var offset = 80;
                var pageContentHeight = 0;

                var pageType = $('div[data-page-no="' + pageNo + '"]').data("page-type");

                if( pageType != undefined && pageType == "gallery") {
                    pageContentHeight = $(".cd-hero-slider li:nth-of-type(" + pageNo + ") .tm-img-gallery-container").height();
                }
                else {
                    pageContentHeight = $(".cd-hero-slider li:nth-of-type(" + pageNo + ") .js-tm-page-content").height() + 20;
                }

                if($(window).width() >= 992) { offset = 120; }
                else if($(window).width() < 480) { offset = 40; }
               
                // Get the page height
                var totalPageHeight = $('.cd-slider-nav').height()
                                        + pageContentHeight + offset
                                        + $('.tm-footer').height();

                // Adjust layout based on page height and window height
                if(totalPageHeight > $(window).height()) 
                {
                    $('.cd-hero-slider').addClass('small-screen');
                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css("min-height", totalPageHeight + "px");
                }
                else 
                {
                    $('.cd-hero-slider').removeClass('small-screen');
                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css("min-height", "100%");
                }
            }

            /*
                Everything is loaded including images.
            */
            $(window).load(function(){

                adjustHeightOfPage(1); // Adjust page height

                /* Gallery One pop up
                -----------------------------------------*/
                $('.gallery-one').magnificPopup({
                    delegate: 'a', // child items selector, by clicking on it popup will open
                    type: 'image',
                    gallery:{enabled:true}                
                });
				
				/* Gallery Two pop up
                -----------------------------------------*/


                /* Gallery Three pop up
                -----------------------------------------*/


                /* Collapse menu after click 
                -----------------------------------------*/
                $('#tmNavbar a').click(function(){
                    $('#tmNavbar').collapse('hide');

                    adjustHeightOfPage($(this).data("no")); // Adjust page height       
                });

                /* Browser resized 
                -----------------------------------------*/
                $( window ).resize(function() {
                    var currentPageNo = $(".cd-hero-slider li.selected .js-tm-page-content").data("page-no");
                    
                    // wait 3 seconds
                    setTimeout(function() {
                        adjustHeightOfPage( currentPageNo );
                    }, 1000);
                    
                });
        
                // Remove preloader (https://ihatetomatoes.net/create-custom-preloading-screen/)
                $('body').addClass('loaded');
                           
            });




        </script>            




</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/32ba8fb0fe.js" crossorigin="anonymous"></script>
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}

</html>

RoomReservationSystem/templates/organization.html
{% extends 'index.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/my_profile.css' %}?v1.3">
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
  <title>Organization Page</title>

{% endblock %}
<style>
  .form-right{
    width: 300px;
    margin-right: 20px;
    margin-top: 10px;
  }
</style>

{% block content %}
  <li class="selected">
    <div class="cd-full-width">
      <div class="container-fluid js-tm-page-content tm-page-pad" data-page-no="5" data-page-type="gallery">
                <br><br><br>
                <div class="container">
                    {% if user_authenticated %}
                    <h1 style="font-size: 32px; margin-bottom: 8px">Organization: {{ orgName }}</h1>  
                    
                     <form action="{% url 'reservationapp:map' %}" class="map" method="get" >
                        {% csrf_token %}
                        <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                        <input type="hidden" name="orgName" value="{{ orgName }}">
                        <input type="hidden" name="list" value="true">
                        <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Map</Button>
                      </form>
                      <form action="{% url 'reservationapp:event' %}" class="event" method="get" >
                        {% csrf_token %}
                        <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                        <input type="hidden" name="orgName" value="{{ orgName }}">
                        <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Events</Button>
                      </form>
                      
                      <form action="{% url 'reservationapp:list-organizations' %}" class="list-organizations" method="get" >
                        {% csrf_token %}
                        <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Back</Button>
                      </form> 

                      <form action="{% url 'reservationapp:logout' %}" class="logout" method="get" > 
                        {% csrf_token %}
              
                        <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Access</Button>
                          
                      </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </li>


{% endblock %}

RoomReservationSystem/templates/roomView.html
{% extends 'index.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/my_profile.css' %}?v1.3">
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
  <title>Organization Page</title>

{% endblock %}
<style>
  .form-right{
    width: 300px;
    margin-right: 20px;
    margin-top: 10px;
  }
</style>

{% block content %}
  <li class="selected">
    <div class="cd-full-width">
      <div class="container-fluid js-tm-page-content tm-page-pad" data-page-no="5" data-page-type="gallery">
                <br><br><br>
                <div class="container">
                    {% if user_authenticated %}
                    <h1 style="font-size: 32px; margin-bottom: 8px">Room Organization: {{ orgName }}</h1>  
                      {% if events %}
                        {%for key,value in events.items %}
                          <p> <b> {{key}}</b></p>
                          {%for event in value%}
                          <p> <b> {{event}}</b></p>
                          {%endfor%}
                        {% endfor %}
                      {% endif %}     
                    {% endif %}
                </div>
                <form action="{% url 'reservationapp:roomView' %}" class="roomView" method="post" >
                    {% csrf_token %}
                    <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                    <input type="hidden" name="orgName" value="{{ orgName }}">
                    <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">List Events</Button>
                </form> 
                <form action="{% url 'reservationapp:event' %}" class="event" method="get" >
                    {% csrf_token %}
                    <input type="hidden" name="orgServerId" value="{{ orgServerId }}">
                    <input type="hidden" name="orgName" value="{{ orgName }}">
                    <Button   style="margin-top: 5px; " class="btn btn-dark btn-lg" type="submit">Back</Button>
                </form> 
            </div>
        </div>
    </li>


{% endblock %}